application: jrawlings-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files: google_appengine

handlers:
- url: /unit6.*
  script: unit6.app
- url: /unit5.*
  script: unit5.app
- url: /unit4.*
  script: unit4.app
- url: /unit3.*
  script: unit3.app
- url: /unit2.*
  script: unit2.app
- url: /unit1*
  script: unit1.app

libraries:
- name: django
  version: "1.2"
- name: jinja2
  version: "2.6"
- name: lxml
  version: "2.3"
- name: markupsafe
  version: "0.15"
- name: numpy
  version: "1.6.1"
- name: PIL
  version: "1.1.7"
- name: pycrypto
  version: "2.3"
- name: setuptools
  version: "0.6c11"
- name: webapp2
  version: "2.3"
- name: webob
  version: "1.1.1"
- name: yaml
  version: "3.10"